name: Build & Push (GHCR)
on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE: ghcr.io/${{ github.repository }}   # ghcr.io/<owner>/<repo>

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE }}:main
            ${{ env.IMAGE }}:${{ github.sha }}