name: Build & Deploy Front (Angular)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: |
            package-lock.json
            **/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Build (production)
        run: npm run build -- --configuration production

      # Descobre automaticamente a subpasta gerada dentro de dist/
      - name: Find dist folder
        id: finddist
        shell: bash
        run: |
          set -e
          APP_DIR="$(ls -d dist/*/ | head -n 1)"
          APP_DIR="${APP_DIR%/}"
          echo "dist_dir=$APP_DIR" >> "$GITHUB_OUTPUT"
          echo "Found dist at: $APP_DIR"
          echo "Conteúdo:"
          ls -la "$APP_DIR"

      # Empacota apenas o CONTEÚDO de dist/<app>
      - name: Pack dist
        shell: bash
        run: |
          mkdir -p package
          tar -czf package/dist.tar.gz -C "${{ steps.finddist.outputs.dist_dir }}" .
          ls -lh package/dist.tar.gz

      # Prepara destino remoto (garante diretório limpo)
      - name: Prepare remote tmp folder
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_KEY }}
          port: 22
          timeout: 60s
          script: |
            set -e
            mkdir -p /root/apps/mindsteps/web/tmp_dist
            rm -rf /root/apps/mindsteps/web/tmp_dist/*

      # Upload do pacote para o DIRETÓRIO (sem tentar renomear)
      - name: Upload dist.tar.gz via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_KEY }}
          port: 22
          timeout: 120s
          source: "package/dist.tar.gz"
          target: "/root/apps/mindsteps/web/tmp_dist"

      # Conferência do que chegou (debug)
      - name: Check uploaded files
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_KEY }}
          port: 22
          timeout: 60s
          script: |
            set -e
            echo "Conteúdo de /tmp_dist:"
            ls -lah /root/apps/mindsteps/web/tmp_dist
            echo "Buscando dist.tar.gz real (arquivo):"
            find /root/apps/mindsteps/web/tmp_dist -type f -name 'dist.tar.gz' -maxdepth 2 -print -quit

      # Deploy atômico: encontra o .tar.gz (independe da subpasta) e extrai
      - name: Atomic replace dist
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_KEY }}
          port: 22
          timeout: 120s
          script: |
            set -e
            BASE=/root/apps/mindsteps/web
            mkdir -p "$BASE/dist" "$BASE/dist_new"

            # Garante rsync e tar
            if ! command -v rsync >/dev/null 2>&1; then
              apt-get update -y && apt-get install -y rsync
            fi
            if ! command -v tar >/dev/null 2>&1; then
              apt-get update -y && apt-get install -y tar
            fi

            # Localiza o arquivo real (pode estar em tmp_dist/ ou tmp_dist/package/)
            PKG="$(find "$BASE/tmp_dist" -type f -name 'dist.tar.gz' -maxdepth 2 -print -quit)"
            if [ -z "$PKG" ]; then
              echo "ERRO: dist.tar.gz não encontrado em $BASE/tmp_dist"; exit 1
            fi
            echo "Usando pacote: $PKG"

            # Extrai conteúdo para staging
            rm -rf "$BASE/dist_new/*"
            tar -xzf "$PKG" -C "$BASE/dist_new"

            # Sincroniza conteúdo para dist/ (sem criar dist/dist)
            rsync -a --delete "$BASE/dist_new/" "$BASE/dist/"

            # Limpeza
            rm -rf "$BASE/tmp_dist" "$BASE/dist_new"
            echo "Deploy concluído. Conteúdo final:"
            ls -lah "$BASE/dist"


            # Limpeza
            rm -rf /root/apps/mindsteps/web/tmp_dist /root/apps/mindsteps/web/dist_new
